### ISSUE TITLE
move year growth from underneath viz to color dropdown

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#20]

**Comment by cnavarreteliz** [comment]
Maybe is too much redundant a dropdrow like as:

- Salary Sum
- Salary Average
- Salary Median
- Growth Salary Sum
- Growth Salary Average
- Growth Salary Median

**Comment by davelandry** [comment]
I don't think it is redundant, but I would put the word "Growth" after the term, so that list would be:

- Salary Sum
- Salary Sum Growth
- Salary Average
- Salary Average Growth
- Salary Median
- Salary Median Growth

**Comment by cnavarreteliz** [comment]
Works fine!

![captura de pantalla 2017-09-30 a la s 22 32 27](https://user-images.githubusercontent.com/5233593/31050883-4827ceee-a62f-11e7-8977-e5a62d066423.png)

In a cube there are 11 measures, and with growth included will be 22 options! I think that I must recognize better options, for example, sort by higher standard deviation because the color variation will be most significant.

Right now, my focus could be remove from dropdown options like "count" in colorScale

**Comment by cnavarreteliz** [comment]
Ahhh @davelandry in the screenshot you can see "Other categories", is 5% lowest categories. Only are grouped if there are more than 15 categories, and I can customize percent of lowest categories.
