### ISSUE TITLE
use blueprint Select dropdowns

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#21]
install with: `npm i @blueprint/labs`

If you have any questions and problems setting it up, please ask and I can bring @alexandersimoes into the conversation to help

**Comment by cnavarreteliz** [comment]
Francisco try to keep Chart icon in the selector

**Comment by frabarz** [comment]
Just commited 675821d4b6a3bf297e7f4fc6a97345ab83ef3ab2, the transition went much more smoothly than I thought.

I think it would be a good opportunity to use the list view to set some kind of <optgroup> with the level hierarchies (instead of putting them in parenthesis like we do now), but I think blueprint's Select can't do that yet.

**Comment by frabarz** [comment]
I still have to fix the "not selected value" state, but the other functions work as intended.

**Comment by davelandry** [comment]
great job @frabarz!
