### ISSUE TITLE
move filters to sidebar and no longer in popup

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#61]
For example:
* when selecting to filter by one or more attributes, it should not do a new data call as I select each attribute, but only when I click the "save" button and close the popup
* when trying to type in a measure filter, it should not fetch new data until I have clicked the "save" button and closed the popup (it currently fetches data on each keystroke!)

**Comment by frabarz** [comment]
Wait, are you sure about fetching data on measure keystrokes?

I'm almost sure it's not possible the way is currently programmed. It has to fetch data if the measure is not in the current aggregator selection, but after that it shouldn't need to fetch it again because the aggregation list is the same and the LoadControl module doesn't see a difference.

Anyway, I suggest a 'Preview' button, since there's no way for the user to know for sure the magnitude of the numbers they're applying, and going back and forth to the Dialog can be cause of friction.

**Comment by davelandry** [comment]
@frabarz I see what you are saying. Let me know if I understand you correctly: we put in a "Show Preview" toggle that toggles between the current behavior and the behavior I have described?

**Comment by frabarz** [comment]
@davelandry I was thinking more on a "Apply changes" button, that changes the filter properties without closing the dialog, to prevent fetching on each keystroke for level filtering, though a toggle is a good idea too

**Comment by davelandry** [comment]
@frabarz ah ok, now I see.

After using the filters for some time, I had an idea: what if we stop putting the filter controls in a Dialog popup, and just put the controls right in the left panel? So, for example, if you chose to "edit" a filter, it would simply expand that filter's area to show the controls. I've made a quick mockup of what that might look like:

![screenshot](https://user-images.githubusercontent.com/1847581/32844189-bb09bee8-c9ef-11e7-8c78-406194651f89.jpg)
